import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

import {
  faSearch,
  faCalendar,
  faGear,
  faUser,
  faEnvelope,
  faAngleDoubleRight,
  faAngleLeft,
  faAngleRight,
  faArrowRightLong,
  faSave,
  faAddressBook,
  faAddressCard,
  faFlag,
  faCity,
  faLock,
  faCircleNotch,
  faPlus,
  faX,
  faPersonWalking,
  faCode,
  faStar,
  faFontAwesome,
  faPen,
  faImage,
  faBook,
  faBagShopping,
} from '@fortawesome/free-solid-svg-icons'

import {
  faGoogle,
  faMicrosoft,
  faApple,
  faPython,
  faVuejs,
  faFigma,
  faJs,
} from '@fortawesome/free-brands-svg-icons'

import { faFlagUsa } from '@fortawesome/free-solid-svg-icons'

library.add(
  faSearch,
  faCalendar,
  faGear,
  faUser,
  faEnvelope,
  faAngleDoubleRight,
  faAngleLeft,
  faAngleRight,
  faArrowRightLong,
  faSave,
  faAddressBook,
  faAddressCard,
  faFlag,
  faCity,
  faLock,
  faCircleNotch,
  faPlus,
  faX,
  faPersonWalking,
  faCode,
  faStar,
  faPen,
  faImage,
  faBook,
  faBagShopping,
  faFontAwesome,
  faPython,
  faVuejs,
  faGoogle,
  faMicrosoft,
  faApple,
  faFigma,
  faJs,
  faFlagUsa,
)

export { FontAwesomeIcon }
